spring.application.name=UserService

spring.datasource.url=jdbc:mysql://localhost:3306/ecomm_user_db
spring.datasource.username=root
spring.datasource.password=Arjunjr@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port= 8081

spring.servlet.multipart.enabled=true

cloudinary.cloud-name=xjdfqkrk
cloudinary.api-key=245888887538989
cloudinary.api-secret=xOmcKa59-V4sq-Q4wEXwlymSqcU

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arjunjr.dev@gmail.com
spring.mail.password=kcpi kucb kwti ffqe

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true